name: Mathics3-Module-vectorizedplot (MS Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows]
        python-version: ['3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        # python -m pip install -e git+https://github.com/Mathics3/mathics-scanner#egg=Mathics-Scanner
        git clone --depth 1 https://github.com/Mathics3/mathics-scanner.git
        cd mathics-scanner/
        pip install -e .
        bash -x admin-tools/make-JSON-tables.sh
        cd ..
        git clone https://github.com/Mathics3/mathics-core
        (cd mathics-core && pip3 install -e .[full])
        (cd mathics-core && bash ./admin-tools/make-JSON-tables.sh)
    - name: Install Mathic3 vectorizedplot Module
      run: |
        python -m pip install Mathics3
        python -m pip install --no-build-isolation -e .
    - name: Test Mathics vectorizedplot
      run: |
        make check
